{
  "hash": "ff390a136c3efbb949d7d615823bb8b3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A Replication of Karlan and List (2007)\"\nauthor: \"Your Name\"\ndate: today\ncallout-appearance: minimal # this hides the blue \"i\" icon on .callout-notes\n---\n\n\n## Introduction\n\nDean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the _American Economic Review_ in 2007. The article and supporting data are available from the [AEA website](https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774) and from Innovations for Poverty Action as part of [Harvard's Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&version=4.2).\n\n_to do: expand on the description of the experiment._\n\nThis project seeks to replicate their results.\n\n\n## Data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load necessary libraries\nlibrary(haven)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load the dataset\ndf <- read_dta(\"karlan_list_2007.dta\")\n\n# Display structure of the data\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 50,083\nColumns: 51\n$ treatment          <dbl> 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, …\n$ control            <dbl> 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, …\n$ ratio              <dbl+lbl> 0, 0, 1, 1, 1, 0, 1, 2, 2, 1, 1, 2, 0, 2, 0, 1,…\n$ ratio2             <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, …\n$ ratio3             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, …\n$ size               <dbl+lbl> 0, 0, 3, 4, 2, 0, 1, 3, 4, 1, 4, 2, 0, 1, 0, 4,…\n$ size25             <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, …\n$ size50             <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, …\n$ size100            <dbl> 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ sizeno             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, …\n$ ask                <dbl+lbl> 0, 0, 1, 1, 1, 0, 3, 3, 2, 2, 1, 3, 0, 2, 0, 1,…\n$ askd1              <dbl> 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, …\n$ askd2              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, …\n$ askd3              <dbl> 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, …\n$ ask1               <dbl> 55, 25, 55, 55, 35, 95, 125, 75, 250, 150, 125, 25,…\n$ ask2               <dbl> 70, 35, 70, 70, 45, 120, 160, 95, 315, 190, 160, 35…\n$ ask3               <dbl> 85, 50, 85, 85, 55, 145, 190, 120, 375, 225, 190, 5…\n$ amount             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ gave               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ amountchange       <dbl> -45, -25, -50, -25, -15, -45, -50, -65, -100, -125,…\n$ hpa                <dbl> 45, 25, 50, 50, 25, 90, 100, 65, 200, 125, 100, 5, …\n$ ltmedmra           <dbl> 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, …\n$ freq               <dbl> 2, 2, 3, 15, 42, 20, 12, 13, 28, 4, 1, 1, 2, 80, 3,…\n$ years              <dbl> 4, 3, 2, 8, 95, 10, 8, 16, 19, 7, 3, 1, 6, 19, 3, 1…\n$ year5              <dbl> 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, …\n$ mrm2               <dbl> 31, 5, 6, 1, 24, 3, 4, 4, 6, 35, 41, 8, 28, 15, 5, …\n$ dormant            <dbl> 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, …\n$ female             <dbl> 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …\n$ couple             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ state50one         <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ nonlit             <dbl> 5, 0, 3, 1, 1, 0, 0, 4, 1, 4, 4, 1, 1, 4, 0, 3, 6, …\n$ cases              <dbl> 4, 2, 1, 2, 1, 0, 1, 3, 1, 3, 3, 2, 1, 1, 1, 1, 2, …\n$ statecnt           <dbl> 4.5002995, 2.9822462, 9.6070213, 3.2814682, 2.30201…\n$ stateresponse      <dbl> 0.01994681, 0.02608696, 0.02304817, 0.02066869, 0.0…\n$ stateresponset     <dbl> 0.019502353, 0.027833002, 0.022158911, 0.024702653,…\n$ stateresponsec     <dbl> 0.020806242, 0.022494888, 0.024743512, 0.012681159,…\n$ stateresponsetminc <dbl> -0.001303889, 0.005338114, -0.002584601, 0.01202149…\n$ perbush            <dbl> 0.4900000, 0.4646465, 0.4081633, 0.4646465, 0.52525…\n$ close25            <dbl> 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, …\n$ red0               <dbl> 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, …\n$ blue0              <dbl> 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, …\n$ redcty             <dbl> 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, …\n$ bluecty            <dbl> 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, …\n$ pwhite             <dbl> 0.4464934, NA, 0.9357064, 0.8883309, 0.7590141, 0.8…\n$ pblack             <dbl> 0.527769208, NA, 0.011948366, 0.010760401, 0.127420…\n$ page18_39          <dbl> 0.3175913, NA, 0.2761282, 0.2794118, 0.4423889, 0.3…\n$ ave_hh_sz          <dbl> 2.10, NA, 2.48, 2.65, 1.85, 2.92, 2.10, 2.47, 2.49,…\n$ median_hhincome    <dbl> 28517, NA, 51175, 79269, 40908, 61779, 54655, 14152…\n$ powner             <dbl> 0.4998072, NA, 0.7219406, 0.9204314, 0.4160721, 0.9…\n$ psch_atlstba       <dbl> 0.32452780, NA, 0.19266793, 0.41214216, 0.43996516,…\n$ pop_propurban      <dbl> 1.0000000, NA, 1.0000000, 1.0000000, 1.0000000, 0.9…\n```\n\n\n:::\n\n```{.r .cell-code}\n# Display summary statistics\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   treatment         control           ratio           ratio2      \n Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000  \n Median :1.0000   Median :0.0000   Median :1.000   Median :0.0000  \n Mean   :0.6668   Mean   :0.3332   Mean   :1.334   Mean   :0.2223  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:0.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :3.000   Max.   :1.0000  \n                                                                   \n     ratio3            size           size25           size50      \n Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :2.000   Median :0.0000   Median :0.0000  \n Mean   :0.2222   Mean   :1.667   Mean   :0.1667   Mean   :0.1666  \n 3rd Qu.:0.0000   3rd Qu.:3.000   3rd Qu.:0.0000   3rd Qu.:0.0000  \n Max.   :1.0000   Max.   :4.000   Max.   :1.0000   Max.   :1.0000  \n                                                                   \n    size100           sizeno            ask            askd1       \n Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000  \n Median :0.0000   Median :0.0000   Median :1.000   Median :0.0000  \n Mean   :0.1667   Mean   :0.1667   Mean   :1.334   Mean   :0.2223  \n 3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:2.000   3rd Qu.:0.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :3.000   Max.   :1.0000  \n                                                                   \n     askd2            askd3             ask1             ask2        \n Min.   :0.0000   Min.   :0.0000   Min.   :  25.0   Min.   :  35.00  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:  35.0   1st Qu.:  45.00  \n Median :0.0000   Median :0.0000   Median :  45.0   Median :  60.00  \n Mean   :0.2223   Mean   :0.2222   Mean   :  71.5   Mean   :  91.79  \n 3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:  65.0   3rd Qu.:  85.00  \n Max.   :1.0000   Max.   :1.0000   Max.   :1500.0   Max.   :1875.00  \n                                                                     \n      ask3          amount              gave          amountchange       \n Min.   :  50   Min.   :  0.0000   Min.   :0.00000   Min.   :-200412.12  \n 1st Qu.:  55   1st Qu.:  0.0000   1st Qu.:0.00000   1st Qu.:    -50.00  \n Median :  70   Median :  0.0000   Median :0.00000   Median :    -30.00  \n Mean   : 111   Mean   :  0.9157   Mean   :0.02065   Mean   :    -52.67  \n 3rd Qu.: 100   3rd Qu.:  0.0000   3rd Qu.:0.00000   3rd Qu.:    -25.00  \n Max.   :2250   Max.   :400.0000   Max.   :1.00000   Max.   :    275.00  \n                                                                         \n      hpa             ltmedmra           freq             years       \n Min.   :   0.00   Min.   :0.0000   Min.   :  0.000   Min.   : 0.000  \n 1st Qu.:  30.00   1st Qu.:0.0000   1st Qu.:  2.000   1st Qu.: 2.000  \n Median :  45.00   Median :0.0000   Median :  4.000   Median : 5.000  \n Mean   :  59.38   Mean   :0.4937   Mean   :  8.039   Mean   : 6.098  \n 3rd Qu.:  60.00   3rd Qu.:1.0000   3rd Qu.: 10.000   3rd Qu.: 9.000  \n Max.   :1000.00   Max.   :1.0000   Max.   :218.000   Max.   :95.000  \n                                                      NA's   :1       \n     year5             mrm2           dormant           female      \n Min.   :0.0000   Min.   :  0.00   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:  4.00   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :1.0000   Median :  8.00   Median :1.0000   Median :0.0000  \n Mean   :0.5088   Mean   : 13.01   Mean   :0.5235   Mean   :0.2777  \n 3rd Qu.:1.0000   3rd Qu.: 19.00   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :168.00   Max.   :1.0000   Max.   :1.0000  \n                  NA's   :1                         NA's   :1111    \n     couple         state50one            nonlit          cases    \n Min.   :0.0000   Min.   :0.0000000   Min.   :0.000   Min.   :0.0  \n 1st Qu.:0.0000   1st Qu.:0.0000000   1st Qu.:1.000   1st Qu.:1.0  \n Median :0.0000   Median :0.0000000   Median :3.000   Median :1.0  \n Mean   :0.0919   Mean   :0.0009983   Mean   :2.474   Mean   :1.5  \n 3rd Qu.:0.0000   3rd Qu.:0.0000000   3rd Qu.:4.000   3rd Qu.:2.0  \n Max.   :1.0000   Max.   :1.0000000   Max.   :6.000   Max.   :4.0  \n NA's   :1148                         NA's   :452     NA's   :452  \n    statecnt         stateresponse     stateresponset    stateresponsec   \n Min.   : 0.001995   Min.   :0.00000   Min.   :0.00000   Min.   :0.00000  \n 1st Qu.: 1.833234   1st Qu.:0.01816   1st Qu.:0.01849   1st Qu.:0.01286  \n Median : 3.538799   Median :0.01971   Median :0.02170   Median :0.01988  \n Mean   : 5.998820   Mean   :0.02063   Mean   :0.02199   Mean   :0.01772  \n 3rd Qu.: 9.607021   3rd Qu.:0.02305   3rd Qu.:0.02470   3rd Qu.:0.02081  \n Max.   :17.368841   Max.   :0.07692   Max.   :0.11111   Max.   :0.05263  \n                                                         NA's   :3        \n stateresponsetminc     perbush           close25            red0       \n Min.   :-0.047619   Min.   :0.09091   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:-0.001388   1st Qu.:0.44444   1st Qu.:0.0000   1st Qu.:0.0000  \n Median : 0.001779   Median :0.48485   Median :0.0000   Median :0.0000  \n Mean   : 0.004273   Mean   :0.48794   Mean   :0.1857   Mean   :0.4045  \n 3rd Qu.: 0.010545   3rd Qu.:0.52525   3rd Qu.:0.0000   3rd Qu.:1.0000  \n Max.   : 0.111111   Max.   :0.73196   Max.   :1.0000   Max.   :1.0000  \n NA's   :3           NA's   :35        NA's   :35       NA's   :35      \n     blue0            redcty          bluecty           pwhite       \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00942  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.75584  \n Median :1.0000   Median :1.0000   Median :0.0000   Median :0.87280  \n Mean   :0.5955   Mean   :0.5102   Mean   :0.4887   Mean   :0.81960  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.93883  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.00000  \n NA's   :35       NA's   :105      NA's   :105      NA's   :1866     \n     pblack          page18_39        ave_hh_sz     median_hhincome \n Min.   :0.00000   Min.   :0.0000   Min.   :0.000   Min.   :  5000  \n 1st Qu.:0.01473   1st Qu.:0.2583   1st Qu.:2.210   1st Qu.: 39181  \n Median :0.03655   Median :0.3055   Median :2.440   Median : 50673  \n Mean   :0.08671   Mean   :0.3217   Mean   :2.429   Mean   : 54816  \n 3rd Qu.:0.09088   3rd Qu.:0.3691   3rd Qu.:2.660   3rd Qu.: 66005  \n Max.   :0.98962   Max.   :0.9975   Max.   :5.270   Max.   :200001  \n NA's   :2036      NA's   :1866     NA's   :1862    NA's   :1874    \n     powner        psch_atlstba    pop_propurban   \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.5602   1st Qu.:0.2356   1st Qu.:0.8849  \n Median :0.7123   Median :0.3737   Median :1.0000  \n Mean   :0.6694   Mean   :0.3917   Mean   :0.8720  \n 3rd Qu.:0.8168   3rd Qu.:0.5300   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n NA's   :1869     NA's   :1868     NA's   :1866    \n```\n\n\n:::\n:::\n\n\n### Description\n\n_todo: Read the data into R/Python and describe the data_\n# Summarize donation outcomes by treatment condition\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>%\n    group_by(treatment) %>%\n    summarise(\n    total_donors = sum(gave),\n    total_amount = sum(amount),\n    avg_amount = mean(amount[gave == 1], na.rm = TRUE),\n    response_rate = mean(gave)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  treatment total_donors total_amount avg_amount response_rate\n      <dbl>        <dbl>        <dbl>      <dbl>         <dbl>\n1         0          298       13571        45.5        0.0179\n2         1          736       32290.       43.9        0.0220\n```\n\n\n:::\n:::\n\n\n:::: {.callout-note collapse=\"true\"}\n### Variable Definitions\n\n| Variable             | Description                                                         |\n|----------------------|---------------------------------------------------------------------|\n| `treatment`          | Treatment                                                           |\n| `control`            | Control                                                             |\n| `ratio`              | Match ratio                                                         |\n| `ratio2`             | 2:1 match ratio                                                     |\n| `ratio3`             | 3:1 match ratio                                                     |\n| `size`               | Match threshold                                                     |\n| `size25`             | \\$25,000 match threshold                                            |\n| `size50`             | \\$50,000 match threshold                                            |\n| `size100`            | \\$100,000 match threshold                                           |\n| `sizeno`             | Unstated match threshold                                            |\n| `ask`                | Suggested donation amount                                           |\n| `askd1`              | Suggested donation was highest previous contribution                |\n| `askd2`              | Suggested donation was 1.25 x highest previous contribution         |\n| `askd3`              | Suggested donation was 1.50 x highest previous contribution         |\n| `ask1`               | Highest previous contribution (for suggestion)                      |\n| `ask2`               | 1.25 x highest previous contribution (for suggestion)               |\n| `ask3`               | 1.50 x highest previous contribution (for suggestion)               |\n| `amount`             | Dollars given                                                       |\n| `gave`               | Gave anything                                                       |\n| `amountchange`       | Change in amount given                                              |\n| `hpa`                | Highest previous contribution                                       |\n| `ltmedmra`           | Small prior donor: last gift was less than median \\$35              |\n| `freq`               | Number of prior donations                                           |\n| `years`              | Number of years since initial donation                              |\n| `year5`              | At least 5 years since initial donation                             |\n| `mrm2`               | Number of months since last donation                                |\n| `dormant`            | Already donated in 2005                                             |\n| `female`             | Female                                                              |\n| `couple`             | Couple                                                              |\n| `state50one`         | State tag: 1 for one observation of each of 50 states; 0 otherwise  |\n| `nonlit`             | Nonlitigation                                                       |\n| `cases`              | Court cases from state in 2004-5 in which organization was involved |\n| `statecnt`           | Percent of sample from state                                        |\n| `stateresponse`      | Proportion of sample from the state who gave                        |\n| `stateresponset`     | Proportion of treated sample from the state who gave                |\n| `stateresponsec`     | Proportion of control sample from the state who gave                |\n| `stateresponsetminc` | stateresponset - stateresponsec                                     |\n| `perbush`            | State vote share for Bush                                           |\n| `close25`            | State vote share for Bush between 47.5% and 52.5%                   |\n| `red0`               | Red state                                                           |\n| `blue0`              | Blue state                                                          |\n| `redcty`             | Red county                                                          |\n| `bluecty`            | Blue county                                                         |\n| `pwhite`             | Proportion white within zip code                                    |\n| `pblack`             | Proportion black within zip code                                    |\n| `page18_39`          | Proportion age 18-39 within zip code                                |\n| `ave_hh_sz`          | Average household size within zip code                              |\n| `median_hhincome`    | Median household income within zip code                             |\n| `powner`             | Proportion house owner within zip code                              |\n| `psch_atlstba`       | Proportion who finished college within zip code                     |\n| `pop_propurban`      | Proportion of population urban within zip code                      |\n\n::::\n\n\n### Balance Test \n\nAs an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.\n\n_todo: test a few variables other than the key outcome variables (for example, test months since last donation) to see if the treatment and control groups are statistically significantly different at the 95% confidence level. Do each as a t-test and separately as a linear regression, and confirm you get the exact same results from both methods. When doing a t-test, use the formula in the class slides. When doing the linear regression, regress for example mrm2 on treatment and look at the estimated coefficient on the treatment variable. It might be helpful to compare parts of your analysis to Table 1 in the paper. Be sure to comment on your results (hint: why is Table 1 included in the paper)._\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# t-tests\nt.test(mrm2 ~ treatment, data = df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  mrm2 by treatment\nt = -0.11953, df = 33394, p-value = 0.9049\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -0.2381015  0.2107298\nsample estimates:\nmean in group 0 mean in group 1 \n       12.99814        13.01183 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(female ~ treatment, data = df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  female by treatment\nt = 1.7535, df = 32451, p-value = 0.07952\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -0.0008888548  0.0159826921\nsample estimates:\nmean in group 0 mean in group 1 \n      0.2826978       0.2751509 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(years ~ treatment, data = df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  years by treatment\nt = 1.0909, df = 32401, p-value = 0.2753\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -0.04584866  0.16094698\nsample estimates:\nmean in group 0 mean in group 1 \n       6.135914        6.078365 \n```\n\n\n:::\n:::\n\n# Linear regression balance check\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(mrm2 ~ treatment, data = df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mrm2 ~ treatment, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-13.012  -9.012  -5.012   6.002 154.988 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 12.99814    0.09353 138.979   <2e-16 ***\ntreatment    0.01369    0.11453   0.119    0.905    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.08 on 50080 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  2.851e-07,\tAdjusted R-squared:  -1.968e-05 \nF-statistic: 0.01428 on 1 and 50080 DF,  p-value: 0.9049\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lm(female ~ treatment, data = df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = female ~ treatment, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-0.2827 -0.2752 -0.2752  0.7173  0.7248 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.282698   0.003504  80.688   <2e-16 ***\ntreatment   -0.007547   0.004292  -1.758   0.0787 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4478 on 48970 degrees of freedom\n  (1111 observations deleted due to missingness)\nMultiple R-squared:  6.313e-05,\tAdjusted R-squared:  4.271e-05 \nF-statistic: 3.092 on 1 and 48970 DF,  p-value: 0.07869\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lm(years ~ treatment, data = df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = years ~ treatment, data = df)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-6.136 -4.136 -1.136  2.864 88.922 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  6.13591    0.04260 144.023   <2e-16 ***\ntreatment   -0.05755    0.05217  -1.103     0.27    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.503 on 50080 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  2.429e-05,\tAdjusted R-squared:  4.327e-06 \nF-statistic: 1.217 on 1 and 50080 DF,  p-value: 0.27\n```\n\n\n:::\n:::\n\n## Experimental Results\n### Balance Test\n\nTo verify the randomization, we tested whether the treatment and control groups differ significantly on a few pre-treatment characteristics.\n\nWe compared:\n- **Months since last donation** (`mrm2`)\n- **Gender (female)** (`female`)\n- **Years since first donation** (`years`)\n\nWe did this both using **Welch two-sample t-tests** and **simple linear regressions**, regressing each variable on the treatment indicator.\n\n#### T-Test Results:\n- `mrm2`: p = 0.905 → **no difference**\n- `female`: p = 0.080 → **not significant** at 95%, but somewhat close\n- `years`: p = 0.275 → **no difference**\n\n#### Regression Results:\n- Coefficient on `treatment` for `mrm2`: 0.014 (p = 0.905)\n- Coefficient on `treatment` for `female`: -0.0075 (p = 0.079)\n- Coefficient on `treatment` for `years`: -0.058 (p = 0.27)\n\nThe results are consistent across both methods and match **Table 1 in Karlan & List (2007)** — there are **no statistically significant differences**, supporting the validity of the randomization process. This reassures us that any treatment effects we detect later are unlikely to be driven by pre-existing group differences.\n\n\n### Charitable Contribution Made\n\nFirst, I analyze whether matched donations lead to an increased response rate of making a donation. \n\n_todo: make a barplot with two bars. Each bar is the proportion of people who donated. One bar for treatment and one bar for control._\n\n_todo: run a t-test between the treatment and control groups on the binary outcome of whether any charitable donation was made. Also run a bivariate linear regression that demonstrates the same finding. (It may help to confirm your calculations match Table 2a Panel A.) Report your statistical results and interpret them in the context of the experiment (e.g., if you found a difference with a small p-value or that was statistically significant at some threshold, what have you learned about human behavior? Use mostly English words, not numbers or stats, to explain your finding.)_\n\n::: {.cell}\n\n```{.r .cell-code}\n# Barplot: Proportion who donated by treatment status\ndf %>%\n    group_by(treatment) %>%\n    summarise(response_rate = mean(gave)) %>%\n    mutate(group = if_else(treatment == 1, \"Treatment\", \"Control\")) %>%\n    ggplot(aes(x = group, y = response_rate, fill = group)) +\n    geom_col(width = 0.5) +\n    labs(\n    title = \"Proportion of Individuals Who Donated\",\n    x = \"Group\",\n    y = \"Response Rate\"\n    ) +\n    theme_minimal() +\n    theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](hw1_questions_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-test on donation rates\nt.test(gave ~ treatment, data = df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  gave by treatment\nt = -3.2095, df = 36577, p-value = 0.001331\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -0.006733310 -0.001627399\nsample estimates:\nmean in group 0 mean in group 1 \n     0.01785821      0.02203857 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Linear regression (bivariate)\nsummary(lm(gave ~ treatment, data = df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = gave ~ treatment, data = df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.02204 -0.02204 -0.02204 -0.01786  0.98214 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.017858   0.001101  16.225  < 2e-16 ***\ntreatment   0.004180   0.001348   3.101  0.00193 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1422 on 50081 degrees of freedom\nMultiple R-squared:  0.000192,\tAdjusted R-squared:  0.0001721 \nF-statistic: 9.618 on 1 and 50081 DF,  p-value: 0.001927\n```\n\n\n:::\n:::\n\n#### Charitable Contribution Made\n\nTo measure whether the matching offer increased the likelihood of giving, I compared the **proportion of individuals who donated** in the treatment vs. control groups.\n\nFrom a simple bar plot, the treatment group clearly had a **higher donation rate**.\n\nThen I ran both a t-test and a linear regression:\n\n- **T-Test**: The difference in donation rates is statistically significant (p = 0.0013), with the treatment group donating **about 0.42 percentage points more** than the control group.\n- **Regression**: A bivariate OLS confirms this — being in the treatment group is associated with a **0.00418 increase in probability of donating**.\n\nTogether, these results suggest that people are **more likely to donate when they’re told their donation will be matched**. This aligns with behavioral economics — people may perceive greater value or urgency when their contribution is effectively “worth more.” Even though the absolute change is small, it's meaningful in a large-scale campaign context.\n\n\n_todo: run a probit regression where the outcome variable is whether any charitable donation was made and the explanatory variable is assignment to treatment or control. Confirm that your results replicate Table 3 column 1 in the paper._\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probit model: whether a donation was made ~ treatment assignment\nsummary(glm(gave ~ treatment, data = df, family = binomial(link = \"probit\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = gave ~ treatment, family = binomial(link = \"probit\"), \n    data = df)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -2.10014    0.02332 -90.074  < 2e-16 ***\ntreatment    0.08678    0.02788   3.113  0.00185 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 10071  on 50082  degrees of freedom\nResidual deviance: 10061  on 50081  degrees of freedom\nAIC: 10065\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n#### Probit Regression: Probability of Donation\n\nTo model the probability of donation using a nonlinear link, I estimated a **probit model** with `gave` as the dependent variable and `treatment` as the independent variable.\n\nThe probit results show:\n- A **positive and statistically significant** coefficient for `treatment` (0.087, p = 0.0019),\n- Meaning individuals assigned to the matching offer were significantly more likely to donate.\n\nThis confirms the earlier t-test and OLS findings — and matches **Table 3, Column 1** of the paper. The matching offer increased donation likelihood. While the numerical change is small, in large-scale campaigns even modest increases in donor response rates can translate to substantial revenue gains.\n\nOverall, this analysis shows that **matching offers matter** — not necessarily because they increase each individual’s donation size, but because they **nudge more people to give in the first place**.\n\n### Differences between Match Rates\n\nNext, I assess the effectiveness of different sizes of matched donations on the response rate.\n\n_todo: Use a series of t-tests to test whether the size of the match ratio has an effect on whether people donate or not. For example, does the 2:1 match rate lead increase the likelihood that someone donates as compared to the 1:1 match rate? Do your results support the \"figures suggest\" comment the authors make on page 8?_\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter treatment group only (exclude control)\ndf_ratio <- df %>% filter(ratio > 0)\n\n# t-tests between match ratios\nt.test(gave ~ ratio, data = df_ratio %>% filter(ratio %in% c(1, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  gave by ratio\nt = -0.96505, df = 22225, p-value = 0.3345\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n -0.005711275  0.001942773\nsample estimates:\nmean in group 1 mean in group 2 \n     0.02074912      0.02263338 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(gave ~ ratio, data = df_ratio %>% filter(ratio %in% c(2, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  gave by ratio\nt = -0.050116, df = 22261, p-value = 0.96\nalternative hypothesis: true difference in means between group 2 and group 3 is not equal to 0\n95 percent confidence interval:\n -0.004012044  0.003811996\nsample estimates:\nmean in group 2 mean in group 3 \n     0.02263338      0.02273340 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(gave ~ ratio, data = df_ratio %>% filter(ratio %in% c(1, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  gave by ratio\nt = -1.015, df = 22215, p-value = 0.3101\nalternative hypothesis: true difference in means between group 1 and group 3 is not equal to 0\n95 percent confidence interval:\n -0.005816051  0.001847501\nsample estimates:\nmean in group 1 mean in group 3 \n     0.02074912      0.02273340 \n```\n\n\n:::\n:::\n\n\n_todo: Assess the same issue using a regression. Specifically, create the variable `ratio1` then regress `gave` on `ratio1`, `ratio2`, and `ratio3` (or alternatively, regress `gave` on the categorical variable `ratio`). Interpret the coefficients and their statistical precision._\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regression using indicator variables for match ratios\ndf_ratio <- df_ratio %>%\n    mutate(\n    ratio1 = if_else(ratio == 1, 1, 0),\n    ratio2 = if_else(ratio == 2, 1, 0),\n    ratio3 = if_else(ratio == 3, 1, 0)\n    )\n\nsummary(lm(gave ~ ratio1 + ratio2 + ratio3, data = df_ratio))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = gave ~ ratio1 + ratio2 + ratio3, data = df_ratio)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.02273 -0.02273 -0.02263 -0.02075  0.97925 \n\nCoefficients: (1 not defined because of singularities)\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.022733   0.001392  16.335   <2e-16 ***\nratio1      -0.001984   0.001968  -1.008    0.313    \nratio2      -0.000100   0.001968  -0.051    0.959    \nratio3             NA         NA      NA       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1468 on 33393 degrees of freedom\nMultiple R-squared:  3.865e-05,\tAdjusted R-squared:  -2.124e-05 \nF-statistic: 0.6454 on 2 and 33393 DF,  p-value: 0.5245\n```\n\n\n:::\n:::\n\n\n_todo: Calculate the response rate difference between the 1:1 and 2:1 match ratios and the 2:1 and 3:1 ratios.  Do this directly from the data, and do it by computing the differences in the fitted coefficients of the previous regression. what do you conclude regarding the effectiveness of different sizes of matched donations?_\n\n::: {.cell}\n\n```{.r .cell-code}\n# Response rates by ratio (filtered to treatment group)\ndf_ratio %>%\n    group_by(ratio) %>%\n    summarise(response_rate = mean(gave))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  ratio     response_rate\n  <dbl+lbl>         <dbl>\n1 1                0.0207\n2 2                0.0226\n3 3                0.0227\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Differences\n# 2:1 - 1:1\ndf_ratio %>% filter(ratio == 2) %>% summarise(mean(gave)) -\ndf_ratio %>% filter(ratio == 1) %>% summarise(mean(gave))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mean(gave)\n1 0.001884251\n```\n\n\n:::\n\n```{.r .cell-code}\n# 3:1 - 2:1\ndf_ratio %>% filter(ratio == 3) %>% summarise(mean(gave)) -\ndf_ratio %>% filter(ratio == 2) %>% summarise(mean(gave))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   mean(gave)\n1 0.000100024\n```\n\n\n:::\n:::\n\n### Differences Between Match Rates\n\nNext, I assessed whether **larger match ratios (e.g., $2:$1 or $3:$1)** actually led to higher response rates compared to the standard $1:$1 match.\n\n#### T-Test Results:\nI ran t-tests comparing the likelihood of donating between different match ratios. None of the differences were statistically significant at the 95% level:\n- **$2:$1 vs $1:$1**: p = 0.33\n- **$3:$1 vs $2:$1**: p = 0.96\n- **$3:$1 vs $1:$1**: p = 0.31\n\nThese results align with what Karlan & List (2007) state: \"larger match ratios... had no additional impact.\"\n\n#### Regression Results:\nI regressed `gave` on binary indicators for each match ratio. Using $3:$1 as the base group, both the $1:$1 and $2:$1 groups had slightly lower donation rates, but again, the differences were **not statistically significant**.\n\n- $1:$1: –0.20 percentage points\n- $2:$1: –0.01 percentage points\n\n#### Direct Comparison of Response Rates:\nFrom the raw data:\n- $1:$1 match: **2.07%** response rate\n- $2:$1 match: **2.26%**\n- $3:$1 match: **2.27%**\n\nDifference between:\n- $2:$1 and $1:$1: **+0.19 percentage points**\n- $3:$1 and $2:$1: **+0.01 percentage points**\n\n#### Conclusion:\nWhile all match treatments increased donation rates over the control group, **larger match ratios didn’t generate additional gains**. This challenges the common intuition among fundraisers that a bigger match is always more compelling. Instead, it seems that the **presence of a match**, rather than its size, is what nudges behavior.\n\n### Size of Charitable Contribution\n\nIn this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.\n\n_todo: Calculate a t-test or run a bivariate linear regression of the donation amount on the treatment status. What do we learn from doing this analysis?_\n\n::: {.cell}\n\n```{.r .cell-code}\n# Linear regression on donation amount (includes zeros)\nsummary(lm(amount ~ treatment, data = df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = amount ~ treatment, data = df)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -0.97  -0.97  -0.97  -0.81 399.03 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.81327    0.06742  12.063   <2e-16 ***\ntreatment    0.15361    0.08256   1.861   0.0628 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.709 on 50081 degrees of freedom\nMultiple R-squared:  6.911e-05,\tAdjusted R-squared:  4.915e-05 \nF-statistic: 3.461 on 1 and 50081 DF,  p-value: 0.06282\n```\n\n\n:::\n:::\n\n_todo: now limit the data to just people who made a donation and repeat the previous analysis. This regression allows you to analyze how much respondents donate conditional on donating some positive amount. Interpret the regression coefficients -- what did we learn? Does the treatment coefficient have a causal interpretation?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Limit to people who donated\ndf_donors <- df %>% filter(gave == 1)\n\n# Regression: amount ~ treatment (conditional on giving)\nsummary(lm(amount ~ treatment, data = df_donors))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = amount ~ treatment, data = df_donors)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-43.54 -23.87 -18.87   6.13 356.13 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   45.540      2.423  18.792   <2e-16 ***\ntreatment     -1.668      2.872  -0.581    0.561    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 41.83 on 1032 degrees of freedom\nMultiple R-squared:  0.0003268,\tAdjusted R-squared:  -0.0006419 \nF-statistic: 0.3374 on 1 and 1032 DF,  p-value: 0.5615\n```\n\n\n:::\n:::\n\n\n_todo: Make two plot: one for the treatment group and one for the control. Each plot should be a histogram of the donation amounts only among people who donated. Add a red vertical bar or some other annotation to indicate the sample average for each plot._\n### Histogram: Control Group Donors\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_donors %>%\n    filter(treatment == 0) %>%\n    ggplot(aes(x = amount)) +\n    geom_histogram(binwidth = 5, fill = \"skyblue\", color = \"white\") +\n    geom_vline(aes(xintercept = mean(amount)), color = \"red\", linetype = \"dashed\", size = 1) +\n    labs(title = \"Donation Distribution – Control Group\", x = \"Donation Amount\", y = \"Count\") +\n    theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](hw1_questions_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n### Histogram: Treatment Group Donors\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_donors %>%\n    filter(treatment == 1) %>%\n    ggplot(aes(x = amount)) +\n    geom_histogram(binwidth = 5, fill = \"lightgreen\", color = \"white\") +\n    geom_vline(aes(xintercept = mean(amount)), color = \"red\", linetype = \"dashed\", size = 1) +\n    labs(title = \"Donation Distribution – Treatment Group\", x = \"Donation Amount\", y = \"Count\") +\n    theme_minimal()\n```\n\n::: {.cell-output-display}\n![](hw1_questions_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## Simulation Experiment\n\nAs a reminder of how the t-statistic \"works,\" in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.\n\nSuppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made. \n\nFurther suppose that the true distribution of respondents who do get a charitable donation match of any size  is Bernoulli with probability p=0.022 that a donation is made.\n\n### Law of Large Numbers\n\n_to do:  Make a plot like those on slide 43 from our first class and explain the plot to the reader. To do this, you will simulate 100,00 draws from the control distribution and 10,000 draws from the treatment distribution. You'll then calculate a vector of 10,000 differences, and then you'll plot the cumulative average of that vector of differences. Comment on whether the cumulative average approaches the true difference in means._\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Simulate donations (1 = gave, 0 = did not give)\ncontrol_sim <- rbinom(n = 100000, size = 1, prob = 0.018)\ntreatment_sim <- rbinom(n = 100000, size = 1, prob = 0.022)\n\n# Take 10,000 random samples of differences\ndiffs <- treatment_sim[1:10000] - control_sim[1:10000]\n\n# Compute cumulative average difference\ncum_avg_diff <- cumsum(diffs) / seq_along(diffs)\n\n# Plot cumulative average\nlibrary(ggplot2)\ntibble(step = 1:10000, cum_avg = cum_avg_diff) %>%\n    ggplot(aes(x = step, y = cum_avg)) +\n    geom_line(color = \"blue\") +\n    geom_hline(yintercept = 0.004, linetype = \"dashed\", color = \"red\", size = 1) +\n    labs(\n    title = \"Cumulative Average of Simulated Differences in Donation Rates\",\n    x = \"Number of Simulated Observations\",\n    y = \"Cumulative Average (Treatment - Control)\"\n    ) +\n    theme_minimal()\n```\n\n::: {.cell-output-display}\n![](hw1_questions_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n### Central Limit Theorem\n\n_to do: Make 4 histograms like those on slide 44 from our first class at sample sizes 50, 200, 500, and 1000 and explain these plots to the reader. To do this for a sample size of e.g. 50, take 50 draws from each of the control and treatment distributions, and calculate the average difference between those draws. Then repeat that process 999 more times so that you have 1000 averages. Plot the histogram of those averages. Comment on whether zero is in the \"middle\" of the distribution or whether it's in the \"tail.\"_\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\n# Helper function to simulate one round of average difference\nsimulate_diff <- function(n, reps = 1000) {\n    replicate(reps, {\n    control <- rbinom(n = n, size = 1, prob = 0.018)\n    treatment <- rbinom(n = n, size = 1, prob = 0.022)\n    mean(treatment) - mean(control)\n    })\n}\n\n# Run simulations for different sample sizes\ndiff_50 <- simulate_diff(50)\ndiff_200 <- simulate_diff(200)\ndiff_500 <- simulate_diff(500)\ndiff_1000 <- simulate_diff(1000)\n\n# Create combined data frame for plotting\nlibrary(tibble)\nlibrary(dplyr)\nlibrary(ggplot2)\n\ndiffs_df <- bind_rows(\n    tibble(diff = diff_50, sample_size = \"n = 50\"),\n    tibble(diff = diff_200, sample_size = \"n = 200\"),\n    tibble(diff = diff_500, sample_size = \"n = 500\"),\n    tibble(diff = diff_1000, sample_size = \"n = 1000\")\n)\n\n# Plot histograms with larger bins\nggplot(diffs_df, aes(x = diff)) +\n    geom_histogram(binwidth = 0.002, fill = \"steelblue\", color = \"white\") +\n    facet_wrap(~sample_size, scales = \"free_y\") +\n    geom_vline(xintercept = 0, color = \"red\", linetype = \"dashed\") +\n    labs(\n    title = \"Sampling Distribution of Mean Differences (Treatment - Control)\",\n    x = \"Average Difference\",\n    y = \"Count\"\n    ) +\n    theme_minimal()\n```\n\n::: {.cell-output-display}\n![](hw1_questions_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n## Simulation Experiment\n\n### Law of Large Numbers\n\nTo demonstrate the Law of Large Numbers, I simulated 100,000 donation outcomes each for the control group (p = 0.018) and treatment group (p = 0.022). I then took 10,000 differences between matched treatment and control values and plotted the **cumulative average** of those differences over time.\n\nThe resulting line converges smoothly to **0.004**, which is the true difference in population probabilities. This confirms that as the number of samples increases, the average of the observed differences converges to the expected difference — illustrating the Law of Large Numbers.\n\n### Central Limit Theorem\n\nNext, I explored how the **distribution of the sample mean differences** changes as sample size increases. For sample sizes 50, 200, 500, and 1000, I repeatedly took 1000 samples from each group, calculated the difference in means, and plotted histograms of those differences.\n\nWhat we observe:\n- For **n = 50**, the distribution is skewed and noisy.\n- By **n = 200 and especially at n = 500 and 1000**, the distributions are nearly **normal and centered around the true difference (~0.004)**.\n- Most importantly, **zero is in the tails**, not the center, meaning we consistently detect a positive effect as sample size grows.\n\nThis is a clear visual example of the **Central Limit Theorem**: regardless of the underlying Bernoulli distribution, the sampling distribution of the difference in means becomes **normal** as n increases.\n\n\n\n",
    "supporting": [
      "hw1_questions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}